// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDdpQNq9Y3fFhwz8MCtrsvYS2iZgitaec',
    appId: '1:535413410532:web:362490546d06579bd5faf1',
    messagingSenderId: '535413410532',
    projectId: 'dclicmarket-763f5',
    authDomain: 'dclicmarket-763f5.firebaseapp.com',
    storageBucket: 'dclicmarket-763f5.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlIgOCO_LX-CbVORsdolJkYXnAAO0Q2-M',
    appId: '1:535413410532:android:e09f4391c8e46acdd5faf1',
    messagingSenderId: '535413410532',
    projectId: 'dclicmarket-763f5',
    storageBucket: 'dclicmarket-763f5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJTYyE1931NKAth5ebcwcjV7n0VzvO_Is',
    appId: '1:535413410532:ios:c1231bd9867cea9fd5faf1',
    messagingSenderId: '535413410532',
    projectId: 'dclicmarket-763f5',
    storageBucket: 'dclicmarket-763f5.firebasestorage.app',
    iosBundleId: 'com.example.vassanou',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJTYyE1931NKAth5ebcwcjV7n0VzvO_Is',
    appId: '1:535413410532:ios:c1231bd9867cea9fd5faf1',
    messagingSenderId: '535413410532',
    projectId: 'dclicmarket-763f5',
    storageBucket: 'dclicmarket-763f5.firebasestorage.app',
    iosBundleId: 'com.example.vassanou',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDDdpQNq9Y3fFhwz8MCtrsvYS2iZgitaec',
    appId: '1:535413410532:web:cd7e386ea3414919d5faf1',
    messagingSenderId: '535413410532',
    projectId: 'dclicmarket-763f5',
    authDomain: 'dclicmarket-763f5.firebaseapp.com',
    storageBucket: 'dclicmarket-763f5.firebasestorage.app',
  );
}
